### ISSUE TITLE
Interface needs to know fps

### ISSUE THREAD

**Issue by jceipek** [jceipek/Complete-Galactic-Dominion#2]
How are we going to tell the interface what the frame rate is? This is needed for updating behavior and is necessary for scrolling to be implemented properly.

**Comment by pvarin** [comment]
I don't know enough about how you implemented the interface to fix this. I had to dig through seven different files just to fix the viewport bleeding problem.

**Comment by pvarin** [comment]
The Window has this information right? I can look into it. Maybe the window should have a reference to the interface as an attribute, and every iteration of the game loop it should call one of the interface's methods and give it the frame rate.

**Comment by jkirschner** [comment]
Clock.tick() returns the # of ms since the last tick.

Clock.get_fps() returns the FPS.

---

From: jceipek [reply@reply.github.com]
Sent: Saturday, March 19, 2011 12:16 AM
To: Jared A. Kirschner
Subject: [GitHub] Interface needs to know fps [jceipek/Complete-Galactic-Dominion GH-2]

How are we going to tell the interface what the frame rate is? This is needed for updating behavior and is necessary for scrolling to be implemented properly.

## 

Reply to this email directly or view it on GitHub:
https://github.com/jceipek/Complete-Galactic-Dominion/issues/2

**Comment by jceipek** [comment]
I know that, Jared. That is how game time is being recorded right now.

Actually, the UpdateEvent contains this information already. The interface is a listener, so it should respond to the Update event.
